//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pokemon_bin_sorting_tool.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pokemon_bin_sorting_tool.Resources.Resource_en", typeof(Resource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        internal static string BTGen {
            get {
                return ResourceManager.GetString("BTGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finished ! 的本地化字符串。
        /// </summary>
        internal static string completePrompt {
            get {
                return ResourceManager.GetString("completePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        internal static string completePromptCaption {
            get {
                return ResourceManager.GetString("completePromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing Necessary File 的本地化字符串。
        /// </summary>
        internal static string fileNotExistCaption {
            get {
                return ResourceManager.GetString("fileNotExistCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check if the TXT file exists in the data directory. 的本地化字符串。
        /// </summary>
        internal static string fileNotExistInfo {
            get {
                return ResourceManager.GetString("fileNotExistInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Count: 的本地化字符串。
        /// </summary>
        internal static string LBFileCount {
            get {
                return ResourceManager.GetString("LBFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loop Count: 的本地化字符串。
        /// </summary>
        internal static string LBLoopCount {
            get {
                return ResourceManager.GetString("LBLoopCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start Index: 的本地化字符串。
        /// </summary>
        internal static string LBStartIndex {
            get {
                return ResourceManager.GetString("LBStartIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String Width: 的本地化字符串。
        /// </summary>
        internal static string LBStringWidth {
            get {
                return ResourceManager.GetString("LBStringWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It may be stuck for a while, please be patient~ 的本地化字符串。
        /// </summary>
        internal static string longTimePrompt {
            get {
                return ResourceManager.GetString("longTimePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        internal static string longTimePromptCaption {
            get {
                return ResourceManager.GetString("longTimePromptCaption", resourceCulture);
            }
        }
    }
}
